### ISSUE TITLE
Ask Me Anything?

### ISSUE THREAD

**Issue by sun0225SUN** [sun0225SUN/sun0225SUN#1]
您可以向我提问任何事情？

(但是最好还是再开一个`issues`吧，这样比较有针对性)

```
  ___      _     ___  ___                  
 / _ \    | |    |  \/  |                  
/ /_\ \___| | __ | .  . | ___              
|  _  / __| |/ / | |\/| |/ _ \             
| | | \__ \   <  | |  | |  __/             
\_| |_/___/_|\_\ \_|  |_/\___|             
                                           
                                           
  ___              _   _     _             
 / _ \            | | | |   (_)            
/ /_\ \_ __  _   _| |_| |__  _ _ __   __ _ 
|  _  | '_ \| | | | __| '_ \| | '_ \ / _` |
| | | | | | | |_| | |_| | | | | | | | (_| |
\_| |_/_| |_|\__, |\__|_| |_|_|_| |_|\__, |
              __/ |                   __/ |
             |___/                   |___/

**Comment by ForyoungYu** [comment]
请问贪吃蛇代码贡献图是怎么弄的？

**Comment by sun0225SUN** [comment]
你说巧不巧，我今天刚写了教程😄
### https://sunguoqi.com/2022/01/09/github_01/

**Comment by ForyoungYu** [comment]
妙！

**Comment by shunhua** [comment]
没生成啊 咋回事？

**Comment by sun0225SUN** [comment]
> 没生成啊 咋回事？

您可以说的具体点

**Comment by shunhua** [comment]
> > 没生成啊 咋回事？
> 
> 您可以说的具体点

可以了 生成了 时间设置的问题

**Comment by shunhua** [comment]
3d 图 只能查一年的吗？

**Comment by sun0225SUN** [comment]
> 3d 图 只能查一年的吗？

是的

**Comment by shunhua** [comment]
> > 3d 图 只能查一年的吗？
> 
> 是的

嗯呢 好的

**Comment by shunhua** [comment]
![image](https://user-images.githubusercontent.com/11988030/154442116-dd0603aa-08f7-46d7-baaa-088c417ea8a1.png)
知道怎么在GitHub 主页 把cn 换成国旗模样吗？

**Comment by sun0225SUN** [comment]
似乎`GitHub`的`markdown`渲染器不支持国旗这个`emoji`喂，只支持一部分，:rocket: ⭐ :cupid:
`GitHub`上面的`markdown`渲染器不如`typora`渲染的好，一些H5的东西，GitHub上也不支持渲染。

**Comment by shunhua** [comment]
> 似乎`GitHub`的`markdown`渲染器不支持国旗这个`emoji`喂，只支持一部分，🚀 ⭐ 💘
> 
> `GitHub`上面的`markdown`渲染器不如`typora`渲染的好，某些H5的东西，GitHub上也不支持渲染，只支持一部分。

嗯嗯

**Comment by shunhua** [comment]
工作流每次更新的新图片，主页 还会有缓存啊 还要重新清楚缓存？

**Comment by sun0225SUN** [comment]
> 工作流每次更新的新图片，主页 还会有缓存啊 还要重新清楚缓存？

是的，用`jsDelivr`的CDN加速的资源会有24小时的缓存。
直接引用GitHub图片的话，在国内很可能打不开。
现在`jsDelivr`的CDN加速在国内也用不了了，只能通过邻近国家的服务器提供加速服务。
不过慢归慢，在不翻墙的状态下可以加载图片，所以我仍使用的`jsDelivr`的CDN。

**Comment by shunhua** [comment]
> > 工作流每次更新的新图片，主页 还会有缓存啊 还要重新清楚缓存？
> 
> 是的，用`jsDelivr`的CDN加速的资源会有24小时的缓存。 直接引用GitHub图片的话，在国内很可能打不开。 现在`jsDelivr`的CDN加速在国内也用不了了，只能通过邻近国家的服务器提供加速服务。 不过慢归慢，在不翻墙的状态下可以加载图片，所以我仍使用的`jsDelivr`的CDN。

嗯嗯

**Comment by narutohyc** [comment]
酷炫，下次试试

**Comment by gallifreyCar** [comment]
小孙同学，我是Gallifrey，我还互相加过博客友链，不知道你还记不记得。我最近去实习了（go工程师，24年毕业，提前实习），有点忙，没太更新博客。我最近看你的文章[让面试官眼前一亮，手把手带你打造个性化的 GitHub 首页](https://blog.sunguoqi.com/archives/github_profile_0),重新制作了一下我的github首页，然后我当时看你还没更新github action的内容，就直接用你库里面的github action里面的脚本了，希望你不要介意，愿我们友谊长存

**Comment by sun0225SUN** [comment]
> 小孙同学，我是Gallifrey，我还互相加过博客友链，不知道你还记不记得。我最近去实习了（go工程师，24年毕业，提前实习），有点忙，没太更新博客。我最近看你的文章[让面试官眼前一亮，手把手带你打造个性化的 GitHub 首页](https://blog.sunguoqi.com/archives/github_profile_0),重新制作了一下我的github首页，然后我当时看你还没更新github action的内容，就直接用你库里面的github action里面的脚本了，希望你不要介意，愿我们友谊长存

哈哈，很乐意分享，一起加油，冲冲冲。

**Comment by srall123** [comment]
hello, 感谢你的教程，想请教一个问题。我使用了你的yml和readme部分代码，贪吃蛇动画都是正常的，但是为什么我的contribution graph和我自身的不一样😂，我将${{ github.repository_owner }}更改成自己的id也有一样的问题，我试了一下platane.github.io/snk生成的图像又是正确的。附上链接https://github.com/srall123，可否帮忙一看。

**Comment by Will-Liang** [comment]
小孙同学，请问有WakaTime美化的相关教程吗

**Comment by sun0225SUN** [comment]
emmm，怎么美化？

我当时用的应该是这个仓库：https://github.com/anmol098/waka-readme-stats

不过刚才搜了下，好像这个仓库的功能更丰富些：https://github.com/athul/waka-readme
![image](https://github.com/sun0225SUN/sun0225SUN/assets/79169717/d547fe73-e880-426f-92c4-378c45f68444)

**Comment by Will-Liang** [comment]
> 

谢谢啦

**Comment by Guo-Chenxu** [comment]
hello, 请问一下能借鉴一下你的部分样式嘛 φ(゜▽゜*)♪

**Comment by sun0225SUN** [comment]
当然可以

**Comment by Guo-Chenxu** [comment]
感谢 o(*￣▽￣*)ブ

**Comment by demonq0q** [comment]
## 运行失败
```
Warning: Unexpected input(s) 'SHOW_TITLE', valid inputs are ['entryPoint', 'args', 'GH_TOKEN', 'WAKATIME_API_KEY', 'SECTION_NAME', 'PULL_BRANCH_NAME', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'SHOW_UPDATED_DATE', 'SHOW_TOTAL_CODE_TIME', 'COMMIT_BY_ME', 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'COMMIT_SINGLE', 'LOCALE', 'UPDATED_DATE_FORMAT', 'IGNORED_REPOS', 'SYMBOL_VERSION', 'DEBUG_LOGGING']
Run anmol098/waka-readme-stats@master
/usr/bin/docker run --name wakareadmestatswakareadmestatsmaster_31e0d0 --label cbc8fb --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_TITLE" -e "INPUT_SECTION_NAME" -e "INPUT_PULL_BRANCH_NAME" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_COMMIT_SINGLE" -e "INPUT_LOCALE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_IGNORED_REPOS" -e "INPUT_SYMBOL_VERSION" -e "INPUT_DEBUG_LOGGING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/demonq0q/demonq0q":"/github/workspace" wakareadmestats/waka-readme-stats:master
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line [2](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:2)[30](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:31), in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 212, in main
    init_github_manager()
  File "/waka-readme-stats/manager_github.py", line 22, in init_github_manager
    GitHubManager.prepare_github_env()
  File "/waka-readme-stats/manager_github.py", line [47](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:48), in prepare_github_env
    github = Github(EM.GH_TOKEN)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github/MainClass.py", line 1[50](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:51), in __init__
    auth = Auth.Token(login_or_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github/Auth.py", line 108, in __init__
    assert len(token) > 0
           ^^^^^^^^^^^^^^
AssertionError
```
- 请问这种情况怎么解决，我折腾了两天，也没搞好
- token是没问题的，感觉是其他地方没搞好
- 过来请教一下

**Comment by demonq0q** [comment]
> ## 运行失败
> ```
> Warning: Unexpected input(s) 'SHOW_TITLE', valid inputs are ['entryPoint', 'args', 'GH_TOKEN', 'WAKATIME_API_KEY', 'SECTION_NAME', 'PULL_BRANCH_NAME', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'SHOW_UPDATED_DATE', 'SHOW_TOTAL_CODE_TIME', 'COMMIT_BY_ME', 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'COMMIT_SINGLE', 'LOCALE', 'UPDATED_DATE_FORMAT', 'IGNORED_REPOS', 'SYMBOL_VERSION', 'DEBUG_LOGGING']
> Run anmol098/waka-readme-stats@master
> /usr/bin/docker run --name wakareadmestatswakareadmestatsmaster_31e0d0 --label cbc8fb --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_TITLE" -e "INPUT_SECTION_NAME" -e "INPUT_PULL_BRANCH_NAME" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_COMMIT_SINGLE" -e "INPUT_LOCALE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_IGNORED_REPOS" -e "INPUT_SYMBOL_VERSION" -e "INPUT_DEBUG_LOGGING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/demonq0q/demonq0q":"/github/workspace" wakareadmestats/waka-readme-stats:master
> Traceback (most recent call last):
>   File "/waka-readme-stats/main.py", line [2](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:2)[30](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:31), in <module>
>     run(main())
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/waka-readme-stats/main.py", line 212, in main
>     init_github_manager()
>   File "/waka-readme-stats/manager_github.py", line 22, in init_github_manager
>     GitHubManager.prepare_github_env()
>   File "/waka-readme-stats/manager_github.py", line [47](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:48), in prepare_github_env
>     github = Github(EM.GH_TOKEN)
>              ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/github/MainClass.py", line 1[50](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:51), in __init__
>     auth = Auth.Token(login_or_token)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/github/Auth.py", line 108, in __init__
>     assert len(token) > 0
>            ^^^^^^^^^^^^^^
> AssertionError
> ```
> 
> * 请问这种情况怎么解决，我折腾了两天，也没搞好
> * token是没问题的，感觉是其他地方没搞好
> * 过来请教一下

**Comment by demonq0q** [comment]
> > ## 运行失败
> > ```
> > Warning: Unexpected input(s) 'SHOW_TITLE', valid inputs are ['entryPoint', 'args', 'GH_TOKEN', 'WAKATIME_API_KEY', 'SECTION_NAME', 'PULL_BRANCH_NAME', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'SHOW_UPDATED_DATE', 'SHOW_TOTAL_CODE_TIME', 'COMMIT_BY_ME', 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'COMMIT_SINGLE', 'LOCALE', 'UPDATED_DATE_FORMAT', 'IGNORED_REPOS', 'SYMBOL_VERSION', 'DEBUG_LOGGING']
> > Run anmol098/waka-readme-stats@master
> > /usr/bin/docker run --name wakareadmestatswakareadmestatsmaster_31e0d0 --label cbc8fb --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_TITLE" -e "INPUT_SECTION_NAME" -e "INPUT_PULL_BRANCH_NAME" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_COMMIT_SINGLE" -e "INPUT_LOCALE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_IGNORED_REPOS" -e "INPUT_SYMBOL_VERSION" -e "INPUT_DEBUG_LOGGING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/demonq0q/demonq0q":"/github/workspace" wakareadmestats/waka-readme-stats:master
> > Traceback (most recent call last):
> >   File "/waka-readme-stats/main.py", line [2](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:2)[30](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:31), in <module>
> >     run(main())
> >   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
> >     return runner.run(main)
> >            ^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
> >     return self._loop.run_until_complete(task)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
> >     return future.result()
> >            ^^^^^^^^^^^^^^^
> >   File "/waka-readme-stats/main.py", line 212, in main
> >     init_github_manager()
> >   File "/waka-readme-stats/manager_github.py", line 22, in init_github_manager
> >     GitHubManager.prepare_github_env()
> >   File "/waka-readme-stats/manager_github.py", line [47](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:48), in prepare_github_env
> >     github = Github(EM.GH_TOKEN)
> >              ^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/site-packages/github/MainClass.py", line 1[50](https://github.com/demonq0q/demonq0q/actions/runs/7416257472/job/20180907893#step:3:51), in __init__
> >     auth = Auth.Token(login_or_token)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/site-packages/github/Auth.py", line 108, in __init__
> >     assert len(token) > 0
> >            ^^^^^^^^^^^^^^
> > AssertionError
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * 请问这种情况怎么解决，我折腾了两天，也没搞好
> > * token是没问题的，感觉是其他地方没搞好
> > * 过来请教一下

已解决，是我没设置了好token的问题，参考了一下其他人的文章

**Comment by sun0225SUN** [comment]
@demonq0q 哈哈哈，好的，我刚看到。

最好跟着作者的教程来搞 https://github.com/anmol098/waka-readme-stats

（碎碎念：快趁着这个机会翻译一下，水篇文章 😄 )

**Comment by demonq0q** [comment]
> @demonq0q 哈哈哈，好的，我刚看到。
> 
> 最好跟着作者的教程来搞 https://github.com/anmol098/waka-readme-stats
> 
> （碎碎念：快趁着这个机会翻译一下，水篇文章 😄 )

哈哈哈哈哈哈哈，好主意

**Comment by shutouyabo** [comment]
你的这个博客网站https://guoqi.dev/，能否加上个标签tags菜单呢？
